// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASUgrEKRsN3a7IAd1eqLd0BPgvGBOj4ho',
    appId: '1:83777768242:web:28afad9c8cdd1357d9e52b',
    messagingSenderId: '83777768242',
    projectId: 'zitaproject3',
    authDomain: 'zitaproject3.firebaseapp.com',
    storageBucket: 'zitaproject3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKwqodccThAgtz6frx-ELlKv1U_o7Huzg',
    appId: '1:83777768242:android:b4f0c55e4a14a42fd9e52b',
    messagingSenderId: '83777768242',
    projectId: 'zitaproject3',
    storageBucket: 'zitaproject3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASUgrEKRsN3a7IAd1eqLd0BPgvGBOj4ho',
    appId: '1:83777768242:web:0ff697e637d91a6bd9e52b',
    messagingSenderId: '83777768242',
    projectId: 'zitaproject3',
    authDomain: 'zitaproject3.firebaseapp.com',
    storageBucket: 'zitaproject3.firebasestorage.app',
  );
}
